#ifndef Retoccilus_Definition_h
#define Retoccilus_Definition_h

//Highlighter Regular Expressions
#define RTC_IDE_REGEXP_SINGLE_LINE_COMMENT "//[^\n]*"
#define RTC_IDE_REGEXP_MULTI_LINE_COMMENT_START "/\\*"
#define RTC_IDE_REGEXP_MULTI_LINE_COMMENT_END "\\*/"
#define RTC_IDE_REGEXP_PREPROCESSOR "#[^\n]*"
#define RTC_IDE_REGEXP_NUMBER_DECIMAL "\\b[0-9]+\\b"
#define RTC_IDE_REGEXP_NUMBER_HEX "\\b0[xX][0-9a-fA-F]+\\b"
#define RTC_IDE_REGEXP_NUMBER_OCTAL "\\b0[0-7]+\\b"
#define RTC_IDE_REGEXP_NUMBER_BINARY "\\b0[bB][01]+\\b"
#define RTC_IDE_REGEXP_NUMBER_FLOAT "\\b[0-9]+\\.[0-9]+\\b"
#define RTC_IDE_REGEXP_STRING_APOSTROPHE "'[^']*'"
#define RTC_IDE_REGEXP_STRING_QUOTATION "\"[^\"]*\""
#define RTC_IDE_REGEXP_STRING_RAW_LITERAL "R\"(.*?\\n?)\""
#define RTC_IDE_REGEXP_IDENTIFIER "\\b[A-Za-z_]+[A-Za-z0-9_]*\\b"
//Default Color Palette
#define RTC_COLOR_RED "#FF0000"
#define RTC_COLOR_GREEN "#00FF00"
#define RTC_COLOR_BLUE "#0000FF"
#define RTC_COLOR_YELLOW "#FFFF00"
#define RTC_COLOR_MAGENTA "#FF00FF"
#define RTC_COLOR_CYAN "#00FFFF"
#define RTC_COLOR_WHITE "#FFFFFF"
#define RTC_COLOR_BLACK "#000000"
#define RTC_COLOR_GRAY "#808080"

#define RTC_COLOR_LIGHT_RED "#FF8080"
#define RTC_COLOR_LIGHT_GREEN "#80FF80"
#define RTC_COLOR_LIGHT_BLUE "#8080FF"
#define RTC_COLOR_LIGHT_YELLOW "#FFFF80"
#define RTC_COLOR_LIGHT_MAGENTA "#FF80FF"
#define RTC_COLOR_LIGHT_CYAN "#80FFFF"
#define RTC_COLOR_LIGHT_WHITE "#C0C0C0"
#define RTC_COLOR_LIGHT_BLACK "#404040"
#define RTC_COLOR_LIGHT_GRAY "#A0A0A0"

#define RTC_COLOR_DARK_RED "#800000"
#define RTC_COLOR_DARK_GREEN "#008000"
#define RTC_COLOR_DARK_BLUE "#000080"
#define RTC_COLOR_DARK_YELLOW "#808000"
#define RTC_COLOR_DARK_MAGENTA "#800080"
#define RTC_COLOR_DARK_CYAN "#008080"
#define RTC_COLOR_DARK_WHITE "#808080"
#define RTC_COLOR_DARK_BLACK "#404040"
#define RTC_COLOR_DARK_GRAY "#202020"



#endif